
build:
  version: "1.0"

accounts:
  message: "Welcome to Sachin Sonar's LOANS-PRODUCTION related local APIs "
  contactDetails:
    name: "Sachin Sonar's - Production"
    email: "Sachin@Prod.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345